# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: ![.github/workflows/Analystik.yml](https://github.com/Sub-Olahoop/App-Analistyik/workflows/.github/workflows/Analystik.yml/badge.svg)!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |https://marketingplatform.google.com/home
        echo Add other actions to build,
        echo test, and deploy your project.
# Pixel Poat
curl -X POST \ -F 'data=[ { "event_name": "PageView", "event_time": 1593161965, "user_data": { "fbc": "fb.1.1554763741205.AbCdEfGhIjKlMnOpQrStUvWxYz1234567890", "fbp": "fb.1.1558571054389.1098115397", "em": "309a0a5c3e211326ae75ca18196d301a9bdbd1a882a4d2569511033da23f0abd" } } ]' \ -F 'access_token=<EAALSnO3gFWEBABRNBvhw71TmusiY8XLXQL8kJHCCshjwuxSoR3jbLHhxvACnLb5a8fX37VnlBrtxr1ZAXJwwtvdLPKE8usIe2FsKZCHnihlOhueWlebEPWpZA3Oa2t44fagbgtTBBUdbflbh25L0mkJzceEoBob2CJHpAfrZALnBWd5QXF8JcYeismhdd7kZD>' \ https://graph.facebook.com/v7.0/<694415321126562>/events


